# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unittests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adcoffset',
            options={'verbose_name': 'values of the four ADC offsets'},
        ),
        migrations.AlterModelOptions(
            name='biases',
            options={'verbose_name': 'biases used in the six HEMTs'},
        ),
        migrations.AlterModelOptions(
            name='detectoroutput',
            options={'verbose_name': 'average output of the four detectors'},
        ),
        migrations.AlterModelOptions(
            name='noisetemperatureanalysis',
            options={'verbose_name': 'noise temperature and gain estimates'},
        ),
        migrations.AlterModelOptions(
            name='polarimetertest',
            options={'get_latest_by': 'acquisition_date', 'ordering': ['polarimeter_number', 'acquisition_date'], 'verbose_name': 'test of a polarimetric unit'},
        ),
        migrations.AlterModelOptions(
            name='stabilityanalysis',
            options={'verbose_name': 'noise analysis for tests done in stable conditions'},
        ),
        migrations.AlterModelOptions(
            name='temperatures',
            options={'verbose_name': 'temperatures of the cryochamber'},
        ),
        migrations.AlterModelOptions(
            name='testtype',
            options={'ordering': ['description'], 'verbose_name': 'type of test'},
        ),
        migrations.RenameField(
            model_name='stabilityanalysis',
            old_name='oof_knee_frequency',
            new_name='oof_knee_frequency_hz',
        ),
        migrations.RenameField(
            model_name='stabilityanalysis',
            old_name='sampling_frequency',
            new_name='sampling_frequency_hz',
        ),
        migrations.RenameField(
            model_name='stabilityanalysis',
            old_name='wn_level',
            new_name='wn_level_adu2_rhz',
        ),
        migrations.AlterField(
            model_name='polarimetertest',
            name='acquisition_date',
            field=models.DateField(verbose_name='Date of acquisition (YY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='polarimetertest',
            name='data_file',
            field=models.FileField(max_length=1024, upload_to='unit_test_data/'),
        ),
        migrations.AlterField(
            model_name='polarimetertest',
            name='operators',
            field=models.ManyToManyField(related_name='tests', to='unittests.Operator'),
        ),
    ]
