# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-20 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unittests', '0002_auto_20171117_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biases',
            options={'verbose_name': 'HEMT polarization biases'},
        ),
        migrations.RemoveField(
            model_name='biases',
            name='h0_idrain',
        ),
        migrations.RemoveField(
            model_name='biases',
            name='h0_vdrain',
        ),
        migrations.RemoveField(
            model_name='biases',
            name='h0_vgate',
        ),
        migrations.RemoveField(
            model_name='biases',
            name='h1_idrain',
        ),
        migrations.RemoveField(
            model_name='biases',
            name='h1_vdrain',
        ),
        migrations.RemoveField(
            model_name='biases',
            name='h1_vgate',
        ),
        migrations.RemoveField(
            model_name='biases',
            name='h2_idrain',
        ),
        migrations.RemoveField(
            model_name='biases',
            name='h2_vdrain',
        ),
        migrations.RemoveField(
            model_name='biases',
            name='h2_vgate',
        ),
        migrations.RemoveField(
            model_name='biases',
            name='h3_idrain',
        ),
        migrations.RemoveField(
            model_name='biases',
            name='h3_vdrain',
        ),
        migrations.RemoveField(
            model_name='biases',
            name='h3_vgate',
        ),
        migrations.RemoveField(
            model_name='biases',
            name='h4_idrain',
        ),
        migrations.RemoveField(
            model_name='biases',
            name='h4_vdrain',
        ),
        migrations.RemoveField(
            model_name='biases',
            name='h4_vgate',
        ),
        migrations.RemoveField(
            model_name='biases',
            name='h5_idrain',
        ),
        migrations.RemoveField(
            model_name='biases',
            name='h5_vdrain',
        ),
        migrations.RemoveField(
            model_name='biases',
            name='h5_vgate',
        ),
        migrations.AddField(
            model_name='biases',
            name='drain_current_ha1_mA',
            field=models.FloatField(default=0.0, verbose_name='H0 drain current [mA]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biases',
            name='drain_current_ha2_mA',
            field=models.FloatField(default=0.0, verbose_name='H2 drain current [mA]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biases',
            name='drain_current_ha3_mA',
            field=models.FloatField(default=0.0, verbose_name='H4 drain current [mA]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biases',
            name='drain_current_hb1_mA',
            field=models.FloatField(default=0.0, verbose_name='H1 drain current [mA]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biases',
            name='drain_current_hb2_mA',
            field=models.FloatField(default=0.0, verbose_name='H3 drain current [mA]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biases',
            name='drain_current_hb3_mA',
            field=models.FloatField(default=0.0, verbose_name='H5 drain current [mA]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biases',
            name='drain_voltage_ha1_V',
            field=models.FloatField(default=0.0, verbose_name='H0 drain voltage [V]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biases',
            name='drain_voltage_ha2_V',
            field=models.FloatField(default=0.0, verbose_name='H2 drain voltage [V]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biases',
            name='drain_voltage_ha3_V',
            field=models.FloatField(default=0.0, verbose_name='H4 drain voltage [V]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biases',
            name='drain_voltage_hb1_V',
            field=models.FloatField(default=0.0, verbose_name='H1 drain voltage [V]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biases',
            name='drain_voltage_hb2_V',
            field=models.FloatField(default=0.0, verbose_name='H3 drain voltage [V]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biases',
            name='drain_voltage_hb3_V',
            field=models.FloatField(default=0.0, verbose_name='H5 drain voltage [V]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biases',
            name='gate_voltage_ha1_mV',
            field=models.FloatField(default=0.0, verbose_name='H0 gate voltage [mV]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biases',
            name='gate_voltage_ha2_mV',
            field=models.FloatField(default=0.0, verbose_name='H2 gate voltage [mV]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biases',
            name='gate_voltage_ha3_mV',
            field=models.FloatField(default=0.0, verbose_name='H4 gate voltage [mV]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biases',
            name='gate_voltage_hb1_mV',
            field=models.FloatField(default=0.0, verbose_name='H1 gate voltage [mV]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biases',
            name='gate_voltage_hb2_mV',
            field=models.FloatField(default=0.0, verbose_name='H3 gate voltage [mV]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biases',
            name='gate_voltage_hb3_mV',
            field=models.FloatField(default=0.0, verbose_name='H5 gate voltage [mV]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='polarimetertest',
            name='phsw_state',
            field=models.CharField(choices=[('N/A', 'N/A'), ('0000', '0000'), ('0101', '0101'), ('1010', '1010'), ('switching', 'switching')], default='0000', max_length=12),
        ),
    ]
