# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-20 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unittests', '0003_auto_20171120_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polarimetertest',
            name='phsw_state',
            field=models.CharField(choices=[('N/A', 'N/A'), ('0101', '0101'), ('0110', '0110'), ('switching', 'switching'), ('1010', '1010'), ('1001', '1001')], default='0000', max_length=12),
        ),
    ]
