# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unittests', '0005_auto_20171121_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adcoffset',
            old_name='pwr0_adu',
            new_name='q1_adu',
        ),
        migrations.RenameField(
            model_name='adcoffset',
            old_name='pwr3_adu',
            new_name='q2_adu',
        ),
        migrations.RenameField(
            model_name='adcoffset',
            old_name='pwr1_adu',
            new_name='u1_adu',
        ),
        migrations.RenameField(
            model_name='adcoffset',
            old_name='pwr2_adu',
            new_name='u2_adu',
        ),
        migrations.RenameField(
            model_name='detectoroutput',
            old_name='pwr0_adu',
            new_name='q1_adu',
        ),
        migrations.RenameField(
            model_name='detectoroutput',
            old_name='pwr3_adu',
            new_name='q2_adu',
        ),
        migrations.RenameField(
            model_name='detectoroutput',
            old_name='pwr1_adu',
            new_name='u1_adu',
        ),
        migrations.RenameField(
            model_name='detectoroutput',
            old_name='pwr2_adu',
            new_name='u2_adu',
        ),
    ]
