# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unittests', '0008_auto_20171127_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandpassanalysis',
            name='estimation_method',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='spectralanalysis',
            name='estimation_method',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
