# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unittests', '0009_auto_20171127_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noisetemperatureanalysis',
            old_name='polarimeter_gain',
            new_name='average_gain',
        ),
        migrations.RenameField(
            model_name='noisetemperatureanalysis',
            old_name='polarimeter_gain_err',
            new_name='average_gain_err',
        ),
        migrations.RenameField(
            model_name='noisetemperatureanalysis',
            old_name='gain_product',
            new_name='cross_gain',
        ),
        migrations.RenameField(
            model_name='noisetemperatureanalysis',
            old_name='gain_product_err',
            new_name='cross_gain_err',
        ),
    ]
