# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unittests', '0011_auto_20171128_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatures',
            name='t_cross_guide_1',
            field=models.FloatField(verbose_name='T_Cross1 [K]'),
        ),
        migrations.AlterField(
            model_name='temperatures',
            name='t_cross_guide_2',
            field=models.FloatField(verbose_name='T_Cross2 [K]'),
        ),
        migrations.AlterField(
            model_name='temperatures',
            name='t_load_a_1',
            field=models.FloatField(verbose_name='Tload_A1 [K]'),
        ),
        migrations.AlterField(
            model_name='temperatures',
            name='t_load_a_2',
            field=models.FloatField(verbose_name='Tload_A2 [K]'),
        ),
        migrations.AlterField(
            model_name='temperatures',
            name='t_load_b_1',
            field=models.FloatField(verbose_name='Tload_B1 [K]'),
        ),
        migrations.AlterField(
            model_name='temperatures',
            name='t_load_b_2',
            field=models.FloatField(verbose_name='Tload_B2 [K]'),
        ),
        migrations.AlterField(
            model_name='temperatures',
            name='t_polarimeter_1',
            field=models.FloatField(verbose_name='T_Pol1 [K]'),
        ),
        migrations.AlterField(
            model_name='temperatures',
            name='t_polarimeter_2',
            field=models.FloatField(verbose_name='T_Pol2 [K]'),
        ),
    ]
