# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-15 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unittests', '0013_polarimetertest_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandpassanalysis',
            name='bandwidth_err',
        ),
        migrations.RemoveField(
            model_name='bandpassanalysis',
            name='central_frequency_err',
        ),
        migrations.RemoveField(
            model_name='noisetemperatureanalysis',
            name='average_gain',
        ),
        migrations.RemoveField(
            model_name='noisetemperatureanalysis',
            name='average_gain_err',
        ),
        migrations.RemoveField(
            model_name='noisetemperatureanalysis',
            name='cross_gain',
        ),
        migrations.RemoveField(
            model_name='noisetemperatureanalysis',
            name='cross_gain_err',
        ),
        migrations.RemoveField(
            model_name='spectralanalysis',
            name='oof_alpha_err',
        ),
        migrations.RemoveField(
            model_name='spectralanalysis',
            name='oof_knee_frequency_err',
        ),
        migrations.RemoveField(
            model_name='spectralanalysis',
            name='wn_level_adu2_rhz',
        ),
        migrations.RemoveField(
            model_name='spectralanalysis',
            name='wn_level_err',
        ),
    ]
