# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-15 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unittests', '0015_auto_20171215_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandpassanalysis',
            name='analysis_date',
        ),
        migrations.RemoveField(
            model_name='bandpassanalysis',
            name='bandwidth_ghz',
        ),
        migrations.RemoveField(
            model_name='bandpassanalysis',
            name='central_frequency_ghz',
        ),
        migrations.RemoveField(
            model_name='bandpassanalysis',
            name='code_commit',
        ),
        migrations.RemoveField(
            model_name='bandpassanalysis',
            name='code_version',
        ),
        migrations.RemoveField(
            model_name='bandpassanalysis',
            name='estimation_method',
        ),
        migrations.RemoveField(
            model_name='noisetemperatureanalysis',
            name='analysis_date',
        ),
        migrations.RemoveField(
            model_name='noisetemperatureanalysis',
            name='code_commit',
        ),
        migrations.RemoveField(
            model_name='noisetemperatureanalysis',
            name='code_version',
        ),
        migrations.RemoveField(
            model_name='noisetemperatureanalysis',
            name='estimation_method',
        ),
        migrations.RemoveField(
            model_name='noisetemperatureanalysis',
            name='noise_temperature',
        ),
        migrations.RemoveField(
            model_name='noisetemperatureanalysis',
            name='noise_temperature_err',
        ),
        migrations.RemoveField(
            model_name='spectralanalysis',
            name='analysis_date',
        ),
        migrations.RemoveField(
            model_name='spectralanalysis',
            name='code_commit',
        ),
        migrations.RemoveField(
            model_name='spectralanalysis',
            name='code_version',
        ),
        migrations.RemoveField(
            model_name='spectralanalysis',
            name='estimation_method',
        ),
        migrations.RemoveField(
            model_name='spectralanalysis',
            name='oof_alpha',
        ),
        migrations.RemoveField(
            model_name='spectralanalysis',
            name='oof_knee_frequency_hz',
        ),
        migrations.RemoveField(
            model_name='spectralanalysis',
            name='sampling_frequency_hz',
        ),
    ]
